name = "khurram-proteins"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "khurram-proteins-db"
database_id = "9cf42922-9a15-40f5-97f5-6185e064a0a7"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "khurram-proteins-images"

[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "77ed7db56d0f42cfbf3959fb4038cd03"

[vars]
R2_PUBLIC_URL = "https://pub-6132f6b6ea2c4d4f9ee0438e1116fa50.r2.dev"
